### ISSUE TITLE
Compatibility with v13 upstream?

### ISSUE THREAD

**Issue by rasos** [libracore/erpnextaustria#8]
Are the extensions compatible only with the libracore flavor of ERPnext or can it be also installed with an up-to-date ERPnext v13.5.0?

**Comment by lasalesi** [comment]
This should be compatible with V13 also from Frappe. In case you find any issues, please do let us know...

**Comment by rasos** [comment]
Yes, installation on v13 latest worked nice. 

Trying now to find out how a "Umsatzsteuervoranmeldung" can be generated (the WIKI does not have an entry on this).
